### ISSUE TITLE
获取小程序请求时候出错BUG

### ISSUE THREAD

**Issue by yumufeng** [swoft-cloud/swoft-http-message#2]
bug文件名称：InteractsWithInput.php

**BUG产生原因**

通过getHeader获取到content-type的数组
然后判断application/json是否存在在getheader获取的数组里面
![1](https://user-images.githubusercontent.com/9146937/42730156-67c43fe8-8820-11e8-8262-e1f9fdba57c3.png)

但是，微信小程序发送的content-type是这样的
![1](https://user-images.githubusercontent.com/9146937/42730167-a625efd4-8820-11e8-845d-7eb379a398e5.png)

所以用in_array就找不到了。会抛异常

修复后如下：
![1](https://user-images.githubusercontent.com/9146937/42730187-faa579b2-8820-11e8-91cc-2b3e7c56f77c.png)

**Comment by inhere** [comment]
```php
int stripos ( string $haystack , string $needle [, int $offset = 0 ] )
```

你参数写反了 `\stripos($contentType, 'application/json')`
